---
title: "DASHBOARD"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(knitr)
library(DT)
library(tidyverse)
library(plotly)
library(highcharter)
library(viridis)
library(openintro)
library(dplyr)
library(ggvis)
```

```{r}
data <- read.csv("C:/Users/ansh/Downloads/vehicle.csv")
view(data)
```

```{r}
mycolor = c("black","darkred","darkorange","darkblue")
``` 

Interactive Data Visualization
===================================
  Row
-----------------------------------

### Car Failure Analysis

  
```{r}
valueBox(paste("Failure"),
         color = "warning")
```

### Car Failures in US

```{r}
valueBox(length(data$State),
         icon = "fa-user")
```

### *Labor Cost*

```{r}
gauge(round(mean(data$lc),
            digits = 2),
      min = 0,
      max = 900,
      gaugeSectors(success = c(0,300),
                   warning = c(300,600),
                   danger = c(600,900),
                  colors=c("green","darkorange","darkred")))
```

### *Maintenance cost*

```{r}
gauge(round(mean(data$mc),
            digits = 2),
      min = 0,
      max = 900,
      gaugeSectors(success = c(0,300),
                   warning = c(300,600),
                   danger = c(600,900),
                   colors=c("green","darkorange","darkred")))
          
```



### Georgia

```{r}
valueBox(sum(data$State == "GA"),
         icon = "fa-building")
```

### California

```{r}
valueBox(sum(data$State == "CA"),
         icon = "fa-building")
```

### Texas

```{r}
valueBox(sum(data$State == "TX"),
         icon = "fa-building")
```

### Florida

```{r}
valueBox(sum(data$State == "FL"),
         icon = "fa-building")
```

Row
------------------------------
  
### Failures by State
  
```{r}
p1 = data %>% 
  group_by(State) %>% 
  summarise(count = n()) %>% 
  plot_ly(x = ~State,
          y = ~count,
          color = "darkorange",
          type = "bar") %>% 
  layout(xaxis = list(title = "Failures By State"),
         yaxis = list(title = "Count"))
p1
```

### Top States

```{r}
p2 = data %>% 
  group_by(State) %>% 
  summarise(count = n()) %>% 
  filter(count>50) %>% 
  plot_ly(labels = ~State,
          values = ~count,
          marker = list(colors = mycolor)) %>% 
  add_pie(hole = 0.2) %>% 
  layout(xaxis = list(zeroline = F,showline = F, showticklabels = F,showgrid = F),yaxis = list(zeroline = F,showline = F, showticklabels = F,showgrid = F))
p2
```

### FM Vs Mileage

```{r}
p3 = plot_ly(data,
             x = ~fm,
             y = ~Mileage,
             text = paste("FM:",data$fm,
                          "Mileage:",data$Mileage),
             type = "bar") %>% 
  layout(xaxis = list(title = "FM"),
         yaxis = list(title = "Failure Mileage"))
p3
```

Row
--------------------------------------------------------------
### Scatter Plot of failure Month Vs Mileage
```{r}
p4 = plot_ly(data,x = ~fm) %>% 
  add_markers(y = ~Mileage,
              text = paste("FM:",data$fm,
                           "Mileage:",data$Mileage),
              showlegend = F) %>% 
  add_lines(y = ~fitted(loess(Mileage~fm)),
            name = "Loess Smoother",
            color = "darkred",
            showlegend = T,
            line = list(width=5)) %>% 
  layout(xaxis = list(title = "Month"),
         yaxis = list(title = "Mileage"))
p4
```

### Scatter Plot of Labor cost Vs labor hour

```{r}
p5 = plot_ly(data,x = ~lc) %>% 
  add_markers(y = ~lh,
              text = paste("LC:",data$lc,
                           "LH:",data$lh),
              showlegend = F) %>% 
  add_lines(y = ~fitted(loess(lc~lh)),
            name = "Loess Smoother",
            color = "darkred",
            showlegend = T,
            line = list(width=5)) %>% 
  layout(xaxis = list(title = "LC"),
         yaxis = list(title = "LH"))
p5
```

Map
==============================================
  
### Map

```{r}
car = data %>% 
  group_by(State) %>% 
  summarise(total = n())
car$State = abbr2state(car$State)

highchart() %>% 
  hc_title(text = "Car Failures in US") %>% 
  hc_subtitle(text = "Source: vehicle.csv") %>% 
  hc_add_series_map(usgeojson,car,name = "State",value = "total",
                    joinBy = c("woename","State")) %>% 
  hc_mapNavigation(enabled = T)
```

Data Table
========================================
  
```{r}
datatable(data,caption = "failure Data",
          rownames = T,
          filter = "top",
          options = list(pageLength = 20))
```

Summary Report
============================================
  Column {data-width = 100}
----------------------------
  
### Max Failure Month
```{r}
valueBox(max(data$fm),
         icon = "fa-user")
```


### Average Labour Cost

```{r}
valueBox(round(mean(data$lc),digits = 2),
         icon = "fa-area-chart")
```

### Average Maintenance Cost
```{r}
valueBox(round(mean(data$mc),digits = 2),
         icon = "fa-area-chart")

```


### Average Mileage at Failure

```{r}
valueBox(round(mean(data$Mileage),digits = 2),
         icon = "fa-area-chart")
```




